//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCSH2BDAS2.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCSH2BDAS2.Helpers.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActingUser.
        /// </summary>
        internal static string ACTING_USER {
            get {
                return ResourceManager.GetString("ACTING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekt v databázi neexistuje.
        /// </summary>
        internal static string DB_DATA_NOT_EXIST {
            get {
                return ResourceManager.GetString("DB_DATA_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string DB_RESPONSE_NO_DATA {
            get {
                return ResourceManager.GetString("DB_RESPONSE_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala chyba.
        /// </summary>
        internal static string GENERIC_ERROR {
            get {
                return ResourceManager.GetString("GENERIC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba serveru.
        /// </summary>
        internal static string GENERIC_SERVER_ERROR {
            get {
                return ResourceManager.GetString("GENERIC_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce úspěšně provedena.
        /// </summary>
        internal static string GENERIC_SUCCESS {
            get {
                return ResourceManager.GetString("GENERIC_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesprávné jméno nebo heslo.
        /// </summary>
        internal static string INVALID_LOGIN {
            get {
                return ResourceManager.GetString("INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedostačující oprávnění.
        /// </summary>
        internal static string INVALID_PERMISSIONS {
            get {
                return ResourceManager.GetString("INVALID_PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatná data požadavku.
        /// </summary>
        internal static string INVALID_REQUEST_DATA {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggedUser.
        /// </summary>
        internal static string LOGGED_USER {
            get {
                return ResourceManager.GetString("LOGGED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno již existuje.
        /// </summary>
        internal static string REGISTER_NAME_EXISTS {
            get {
                return ResourceManager.GetString("REGISTER_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrace proběhla úspěšně.
        /// </summary>
        internal static string REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string TEMPDATA_ERROR {
            get {
                return ResourceManager.GetString("TEMPDATA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        internal static string TEMPDATA_SUCCESS {
            get {
                return ResourceManager.GetString("TEMPDATA_SUCCESS", resourceCulture);
            }
        }
    }
}
